# Modified (by John Neal) from https://github.com/datitran/raccoon_dataset/blob/master/xml_to_csv.py

import os
import glob
import pandas as pd
import xml.etree.ElementTree as ET


def xml_to_csv(path):
    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        root = tree.getroot()
        for member in root.findall('object'):
            value = (root.find('filename').text,
                     int(root.find('size')[0].text),
                     int(root.find('size')[1].text),
                     member[0].text,
                     int(member[4][0].text),
                     int(member[4][1].text),
                     int(member[4][2].text),
                     int(member[4][3].text)
                     )
            xml_list.append(value)
    # This file is tailored for the particular XML file I am decoding.
    # Column names are chosen to match those from XML file generated by labelImg software
    column_name = ['filename', 'width', 'height', 'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


def main():
    image_path = os.path.join(os.getcwd()) # Removed unnecesary field - JN
    print(image_path)
    xml_df = xml_to_csv(image_path)
    print('Enter name of .csv:')
    csv_name = raw_input()
    xml_df.to_csv(csv_name, index=None) # changed csv name - JN
    print('Successfully converted xml to csv.')


main()